# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'sunglass-shop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sunglass-shop
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore', '6.2.0' 

  target 'sunglass-shopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sunglass-shopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
